### ISSUE TITLE
iOS UIWebView agent OS matching

### ISSUE THREAD

**Issue by shabbyrobe** [OpenDDRdotORG/OpenDDR-Java#8]
I get quite a few hits from UIWebView apps that have user agent strings like this:

Almost all of them follow the format `Application Name (iPad; iPhone OS x.y.z; en_US)` and have the iOS version number populated. It matches a device just fine, but fails to match an OS because the iOS operating system matcher is nested inside the Mozilla builder, but these agents don't start with Mozilla.

Unless I'm unaware of a class of device that misuses "iPhone" in its user agent, it seems to me like the IOS builder should be separated out from the Mozilla building hierarchy to enable proper detection of the OS.

**Comment by OpenDDR** [comment]
Dear shabbyrobe,
Do you refer to default user agent setted by UIWebView or to a custom user agent setted by App developers?
Currently we have no evidence of UIWebView that set, by default, an user agent following the pattern you expose.
From our analysis, it seem's that UIWebView's default user agent is pretty equals to user agent setted by default browser (with mozilla Pattern).
As you suppose, some devices use "iPhone" in the userAgent, so we decided to use a "strong" pattern to identify iOS deivces in order to avoid identification error but, if in some versions of iOS, UIWebView sets default user agent following the pattern you suggest, we can create another OsBuilder (IOSUiWebViewBuilder) following that pattern.

Thanks,
OpenDDR Dev. Team

**Comment by shabbyrobe** [comment]
Yep they're non-standard user agent strings that seem to be set by the developers. They all follow such a distinct format though - perhaps they all use a common framework. We get dozens and dozens of them though, and they're all from apps and they all follow the format I mentioned in the first message. Is there a way I can message you privately?
